name: SQL for GitHub Actions
 
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
 
jobs:
  build:
    if: ${{ github.event.pull_request.merged }} == "true" || ${{ github.event_name }}" == "push"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy SQL Project
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './test.sql'
          action: 'publish'

    - name: Logout
      run: ar logout